### ISSUE TITLE
Discussion: Road map to initial release

### ISSUE THREAD

**Issue by johnnyapol** [Unkn0wn-0nes/UnknownNet#13]
So basically the library is in a pretty good state right now. It's mostly stable, a few things have to be ironed out and a few things have to be finished off.

I'd like to just state the road map for whats left to initial release.
- [x] New build system for more professional style builds down the road. Thanks Travis-CI!
- [x] Converted project to maven for easier integration with maven/gradle architectures. 
- [ ] Find some place to upload project to, either Maven Central or Sonatype?
- [ ] Finish administration API
- [ ] Allow custom SSL certificates to be used for SSL communications
- [ ] Allow server software to be a standalone binary.
- [x] Terminate client connections properly
- [x] Make packets poolable objects versus allocating consistently and the broken race-condition prone reuse hack on the client
- [x] Clean up client library code through abstraction
